steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/jobsearch/careernexus', 'frontend/']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/jobsearch/careernexus']

  # Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'careernexus'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/jobsearch/careernexus'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars=^|^GOOGLE_CLOUD_PROJECT=$PROJECT_ID|GOOGLE_CLOUD_LOCATION=${_GOOGLE_CLOUD_LOCATION}|GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}|GOOGLE_API_KEY=${_GOOGLE_API_KEY}|ALLOWED_EMAILS=${_ALLOWED_EMAILS}'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/jobsearch/careernexus'

substitutions:
  _GOOGLE_CLOUD_LOCATION: us-central1
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_API_KEY: ''
  _ALLOWED_EMAILS: 'charlie@workbench-data.com,rankin@workbench-data.com'

options:
  logging: CLOUD_LOGGING_ONLY
