steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jobsearch-backend', 'backend/']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jobsearch-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jobsearch-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jobsearch-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=${_GOOGLE_CLOUD_LOCATION}'
      - '--set-secrets'
      - 'PROXY_HEADER=proxy-header:latest'

images:
  - 'gcr.io/$PROJECT_ID/jobsearch-backend'

substitutions:
  _GOOGLE_CLOUD_LOCATION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
